name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          docker login --username oaaderibigbe --password ${{ secrets.DK_PAT }} docker.io
          docker build . --tag docker.io/oaaderibigbe/githubcontainer:latest
          docker push docker.io/oaaderibigbe/githubcontainer:latest
