name: Nightly Build



on:

  schedule: 

    - cron: "*/10 * * * *"  # Runs every day at midnight UTC

  push: 
    branches: [main]



jobs:

  send_email:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install @sendgrid/mail
      - name: Send email with SendGrid
        env:
          SENDGRID_API_KEY:  ${{ secrets.SENDGRID_API_KEY }} 

        with:

          to: "oaaderibigbe@dons.usfca.edu" 

          subject: "Midnight notification"

          text: "This email was sent at midnight."
